app:
  env: "development"
  port: 4000
db:
  dsn: "postgresql://postgres:postgres@database:5432?database=monolith"
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: "15m"
  timeout: 5
mq:
  dsn: "amqp://rabbitmq:rabbitmq@localhost:5672/monolith"
  maxConns: 10
